### PR TITLE
Add PeopleDataLabs to README.

### PR DESCRIPTION
**Pull request by 0xdade**
[People Data Labs](peopledatalabs.com) came to my attention today after a Twitter thread detailing a targeted phishing campaign noted that it matched their data profile from People Data Labs.

I looked myself up, and looked my friend up with their permission, and found varying level of details. Seems to _mostly_ be scrapable data from social media sites and potentially other people lookup sites, but I'm not sure.

Anyways, I hate them and their business model, so I wanted to contribute back to the BADBOOL list :)

### CODE REVIEW

**Comment by yaelwrites** [comment]
Thank you for sending this in! Can you show me the Twitter thread so I can get some more information? This looks like a B2B site.

**Comment by 0xdade** [comment]
This was the thread that caused me to investigate it. https://twitter.com/parth220_/status/1771589789143478471

I think they are definitely marketed B2B, but also I think their due diligence on "business" is "Do they own a domain name", so I think what they market to and who may actually be able to access the data are very different.

**Comment by yaelwrites** [comment]
Thank you so much for the link. I just made some quick changes today but will investigate this further for the next round of updates.

**Comment by Scrut1ny** [comment]
Make sure to add the opt out link for PeopleDataLabs.

[https://www.peopledatalabs.com/do-not-sell-or-share](Opt Out Form)

**Comment by yaelwrites** [comment]
I’m so sorry to not include this but I only add companies if the user is able to see whether a company has their info or not before opting out to avoid adding information to a database that wasn’t already there.

**Pull request closed without merging**
